library 'cb-days@master'
def testPodYaml = libraryResource 'podtemplates/react/react-test-pod.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '10'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 10)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
    repository = "${repository}"
  }
  stages('React Test and Build')
  {
    stage('React Tests') {
      agent {
        kubernetes {
          label 'nodejs'
          yaml testPodYaml
       }
      }
      steps {
            checkout scm           
            container('nodejs') {
              sh '''
                 npm install
                 '''
            }
      } 
    }
    stage('Debug') {
      environment {
       commitId = sh(returnStdout: true, script: 'git rev-parse HEAD') 
      }
      agent any
      steps {
        sh "echo ${commitId}"
      }
    }
    stage('Build and Push Image') {
      steps { 
        kanikoBuildPushGeneric("${repository}", "${env.GIT_COMMIT}", "${gcpProject}/${repoOwner}")
        {
          checkout scm
        }
      }
    } 
  }
}

